spring.application.name=JAVA_Seminar6

#MySQL konfiguracija lokalajam
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/miniuni
spring.datasource.username=userspring
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name =com.mysql.jdbc.Driver